version: '2'

volumes:
  orderer0.orderer.prototype.rks.plus:
  peer0.executor.prototype.rks.plus:
  peer1.executor.prototype.rks.plus:
  peer0.producer.prototype.rks.plus:
  peer1.producer.prototype.rks.plus:
  peer0.distributor.prototype.rks.plus:
  peer1.distributor.prototype.rks.plus:
  peer0.service.prototype.rks.plus:
  peer1.service.prototype.rks.plus:
  peer0.consumer.prototype.rks.plus:
  peer1.consumer.prototype.rks.plus:
  peer0.supervisor.prototype.rks.plus:
  peer1.supervisor.prototype.rks.plus:

networks:
  basic:

services:

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ExecutorMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/users/Admin@executor.prototype.rks.plus/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer0.orderer.prototype.rks.plus
      - peer0.executor.prototype.rks.plus
      - peer1.executor.prototype.rks.plus
      - peer0.producer.prototype.rks.plus
      - peer1.producer.prototype.rks.plus
      - peer0.distributor.prototype.rks.plus
      - peer1.distributor.prototype.rks.plus
      - peer0.service.prototype.rks.plus
      - peer1.service.prototype.rks.plus
      - peer0.consumer.prototype.rks.plus
      - peer1.consumer.prototype.rks.plus
      - peer0.supervisor.prototype.rks.plus
      - peer1.supervisor.prototype.rks.plus
    networks:
      - basic

  orderer0.orderer.prototype.rks.plus:
    container_name: orderer0.orderer.prototype.rks.plus
    extends:
      file:   ./../docker/core/orderer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/orderer.prototype.rks.plus/orderers/orderer0.orderer.prototype.rks.plus/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/orderer.prototype.rks.plus/orderers/orderer0.orderer.prototype.rks.plus/tls/:/var/hyperledger/orderer/tls
      - orderer0.orderer.prototype.rks.plus:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - basic

  peer:
    extends:
      file:  ./../docker/core/peer-base.yaml
      service: peer-base
    networks:
      - basic

  ca.executor.prototype.rks.plus:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.executor.rks.plus
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.executor.rks.plus-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d2ef4ca8a467f8139f403dfb63f0e19bb02ac378957a88fef5935739ecba82ae_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/executor.rks.plus/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.executor.rks.plus
    networks:
      - basic

  peer0.executor.prototype.rks.plus:
    container_name: peer0.executor.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer0.executor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ExecutorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.executor.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - ca.executor.prototype.rks.plus

  peer1.executor.prototype.rks.plus:
    container_name: peer1.executor.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer1.executor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ExecutorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer1.executor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer1.executor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.executor.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.producer.prototype.rks.plus:
    container_name: peer0.producer.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer0.producer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer0.producer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer0.producer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.producer.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.producer.prototype.rks.plus:
    container_name: peer1.producer.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer1.producer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer1.producer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer1.producer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.producer.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 9151:7051
      - 9153:7053

  peer0.distributor.prototype.rks.plus:
    container_name: peer0.distributor.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer0.distributor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=DistributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer0.distributor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer0.distributor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.distributor.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer1.distributor.prototype.rks.plus:
    container_name: peer1.distributor.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer1.distributor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=DistributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer1.distributor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer1.distributor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.distributor.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 10151:7051
      - 10153:7053

  peer0.service.prototype.rks.plus:
    container_name: peer0.service.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer0.service.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.service.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ServiceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer0.service.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer0.service.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.service.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.service.prototype.rks.plus:
    container_name: peer1.service.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer1.service.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.service.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ServiceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer1.service.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer1.service.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.service.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 11151:7051
      - 11153:7053

  peer0.consumer.prototype.rks.plus:
    container_name: peer0.consumer.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer0.consumer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer0.consumer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer0.consumer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.consumer.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053

  peer1.consumer.prototype.rks.plus:
    container_name: peer1.consumer.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer1.consumer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer1.consumer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer1.consumer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.consumer.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 12151:7051
      - 12153:7053

  peer0.supervisor.prototype.rks.plus:
    container_name: peer0.supervisor.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer0.supervisor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.supervisor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=SupervisorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer0.supervisor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer0.supervisor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.supervisor.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053

  peer1.supervisor.prototype.rks.plus:
    container_name: peer1.supervisor.prototype.rks.plus
    extends:
      service: peer
    environment:
      - CORE_PEER_ID=peer1.supervisor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supervisor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=SupervisorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer1.supervisor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer1.supervisor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.supervisor.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 13151:7051
      - 13153:7053
