version: '2'

volumes:
  orderer0.orderer.prototype.rks.plus:
  peer0.executor.prototype.rks.plus:
  peer1.executor.prototype.rks.plus:
  peer0.producer.prototype.rks.plus:
  peer1.producer.prototype.rks.plus:
  peer0.distributor.prototype.rks.plus:
  peer1.distributor.prototype.rks.plus:
  peer0.service.prototype.rks.plus:
  peer1.service.prototype.rks.plus:
  peer0.consumer.prototype.rks.plus:
  peer1.consumer.prototype.rks.plus:
  peer0.supervisor.prototype.rks.plus:
  peer1.supervisor.prototype.rks.plus:

networks:
  basic:

services:

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ExecutorMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/executor.prototype.rks.plus/users/Admin@executor.prototype.rks.plus/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer0.orderer.prototype.rks.plus
      - peer0.executor.prototype.rks.plus
      - peer1.executor.prototype.rks.plus
      - peer0.producer.prototype.rks.plus
      - peer1.producer.prototype.rks.plus
      - peer0.distributor.prototype.rks.plus
      - peer1.distributor.prototype.rks.plus
      - peer0.service.prototype.rks.plus
      - peer1.service.prototype.rks.plus
      - peer0.consumer.prototype.rks.plus
      - peer1.consumer.prototype.rks.plus
      - peer0.supervisor.prototype.rks.plus
      - peer1.supervisor.prototype.rks.plus
    networks:
      - basic

  orderer0.orderer.prototype.rks.plus:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.orderer.prototype.rks.plus
    container_name: orderer0.orderer.prototype.rks.plus
    networks:
      - basic

  peer0.executor.prototype.rks.plus:
    container_name: peer0.executor.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.executor.prototype.rks.plus
    networks:
      - basic

  peer1.executor.prototype.rks.plus:
    container_name: peer1.executor.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.executor.prototype.rks.plus
    networks:
      - basic

  peer0.producer.prototype.rks.plus:
    container_name: peer0.producer.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.producer.prototype.rks.plus
    networks:
      - basic

  peer1.producer.prototype.rks.plus:
    container_name: peer1.producer.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.producer.prototype.rks.plus
    networks:
      - basic

  peer0.distributor.prototype.rks.plus:
    container_name: peer0.distributor.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.distributor.prototype.rks.plus
    networks:
      - basic

  peer1.distributor.prototype.rks.plus:
    container_name: peer1.distributor.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.distributor.prototype.rks.plus
    networks:
      - basic

  peer0.service.prototype.rks.plus:
    container_name: peer0.service.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.service.prototype.rks.plus
    networks:
      - basic

  peer1.service.prototype.rks.plus:
    container_name: peer1.service.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.service.prototype.rks.plus
    networks:
      - basic

  peer0.consumer.prototype.rks.plus:
    container_name: peer0.consumer.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.consumer.prototype.rks.plus
    networks:
      - basic

  peer1.consumer.prototype.rks.plus:
    container_name: peer1.consumer.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.consumer.prototype.rks.plus
    networks:
      - basic

  peer0.supervisor.prototype.rks.plus:
    container_name: peer0.supervisor.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.supervisor.prototype.rks.plus
    networks:
      - basic

  peer1.supervisor.prototype.rks.plus:
    container_name: peer1.supervisor.prototype.rks.plus
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.supervisor.prototype.rks.plus
    networks:
      - basic
