version: '2'

services:

  orderer0.orderer.prototype.rks.plus:
    container_name: orderer0.orderer.prototype.rks.plus
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/orderer.prototype.rks.plus/orderers/orderer0.orderer.prototype.rks.plus/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/orderer.prototype.rks.plus/orderers/orderer0.orderer.prototype.rks.plus/tls/:/var/hyperledger/orderer/tls
    - orderer0.orderer.prototype.rks.plus:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.executor.prototype.rks.plus:
    container_name: peer0.executor.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.executor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ExecutorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer0.executor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.executor.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.executor.prototype.rks.plus:
    container_name: peer1.executor.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.executor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.executor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.executor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ExecutorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer1.executor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/executor.prototype.rks.plus/peers/peer1.executor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.executor.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.producer.prototype.rks.plus:
    container_name: peer0.producer.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.producer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer0.producer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer0.producer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.producer.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.producer.prototype.rks.plus:
    container_name: peer1.producer.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.producer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.producer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer1.producer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.prototype.rks.plus/peers/peer1.producer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.producer.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 9151:7051
      - 9153:7053

  peer0.distributor.prototype.rks.plus:
    container_name: peer0.distributor.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.distributor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=DistributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer0.distributor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer0.distributor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.distributor.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer1.distributor.prototype.rks.plus:
    container_name: peer1.distributor.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.distributor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.distributor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=DistributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer1.distributor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/distributor.prototype.rks.plus/peers/peer1.distributor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.distributor.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 10151:7051
      - 10153:7053

  peer0.service.prototype.rks.plus:
    container_name: peer0.service.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.service.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.service.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ServiceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer0.service.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer0.service.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.service.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.service.prototype.rks.plus:
    container_name: peer1.service.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.service.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.service.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.service.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ServiceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer1.service.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/service.prototype.rks.plus/peers/peer1.service.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.service.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 11151:7051
      - 11153:7053

  peer0.consumer.prototype.rks.plus:
    container_name: peer0.consumer.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.consumer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer0.consumer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer0.consumer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.consumer.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053

  peer1.consumer.prototype.rks.plus:
    container_name: peer1.consumer.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.consumer.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=ConsumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer1.consumer.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.prototype.rks.plus/peers/peer1.consumer.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.consumer.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 12151:7051
      - 12153:7053

  peer0.supervisor.prototype.rks.plus:
    container_name: peer0.supervisor.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.supervisor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer0.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.supervisor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=SupervisorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer0.supervisor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer0.supervisor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer0.supervisor.prototype.rks.plus:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053

  peer1.supervisor.prototype.rks.plus:
    container_name: peer1.supervisor.prototype.rks.plus
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.supervisor.prototype.rks.plus
      - CORE_PEER_ADDRESS=peer1.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.supervisor.prototype.rks.plus:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supervisor.prototype.rks.plus:7051
      - CORE_PEER_LOCALMSPID=SupervisorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer1.supervisor.prototype.rks.plus/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/supervisor.prototype.rks.plus/peers/peer1.supervisor.prototype.rks.plus/tls:/etc/hyperledger/fabric/tls
        - peer1.supervisor.prototype.rks.plus:/var/hyperledger/production

    ports:
      - 13151:7051
      - 13153:7053
